### ISSUE TITLE
Can't use the XBMC's Power off and Exit when using libcec libs

### ISSUE THREAD

**Issue by steven1758** [xbmc-imx6/xbmc#54]
Hi all

Talked this with wolfgar,thanks his tips to rename all the libcec libs to anther name,
Then it become ok,but can not use the HDMI CEC,
If this problem can be fixed ,it will be more convenience. ; )

Thanks

Kind Regards

steven

**Comment by wolfgar** [comment]
do you us the latest libcec version published [here](https://github.com/xbmc-imx6/libcec) ?

**Comment by steven1758** [comment]
Hi wolfgar

Yea,Just have tried this latest version, still the same problem ,after deleted all the libcec.\* libs ,
then it become ok.

Thanks

**Comment by steven1758** [comment]
and with your old XBMC this version https://github.com/wolfgar/xbmc
works very well. :  )

**Comment by wolfgar** [comment]
hmm I will try to reproduce : The worst is I know this issue because I saw it in the past but I don't have it currently with (apparently) the same sources from libcec and xbmc in this repo ;)
Anyway I almost always have a few deltas in my dev images so I will try with a clean build and check if I can reproduce and investigate...

**Comment by emveepee** [comment]
It might be worth ask Tom why he made this change to GeexBox.
http://hg.openbricks.org/openbricks/rev/e0e1736acffa

**Comment by wolfgar** [comment]
If I remind correctly the 3.10 cec driver has not been adapted, do you confirm tom ?
Apart from this, I have just checked : I reproduce the issue. So I will investigate it tomorrow...

**Comment by tomlohave** [comment]
Le 02/04/2014 03:30, wolfgar a écrit :

> If I remind correctly the 3.10 cec driver has not been adapted, do you 
> confirm tom ?
> 
> Exactly, something I have tried without success.
> but even with the kernel part, if you try to stop or reboot on xbmc 
> (using 3.10 kernel and cec enabled on xbmc), xbmc logs say xbmc is 
> terminated, while thread is not
> on Utilite, kernel 3.0.35,I found one problem maybe related to this. if 
> you try to stop cec component using peripheral menu, system freezes
> 
> Apart from this, I have just checked : I reproduce the issue. So I 
> will investigate it tomorrow...
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/xbmc-imx6/xbmc/issues/54#issuecomment-39280426.

## 

www.geexbox.org
mailto:tomlohave@openbricks.org

**Comment by steven1758** [comment]
Yea,It is very right ,but after remove this, We can not use the HDMI-CEC now.
it will be very good if we can fix this problem :  )

**Comment by mk01** [comment]
@colleagues,

poweroff and restart disappeared only few days ago with some of Gotham pulls (personally I have all pulled from upstream). It was there with Beta3 for sure. Actually I realised this 2 days ago only so don't know exactly. 

later edit:
just removed "upower" package and SHUTDOWN and REBOOT is back.

**Comment by wolfgar** [comment]
Please apply this kernel patch and you should not have the issue any longer : [patch](https://github.com/wolfgar/utilite/commit/342b93f740d53291fcef3f56df4ee00e96b302cb)

there were 2 issues which can lead to the blocking situation : a big mistake in poll implementation (They -fsl dev- tried to return negative error codes while poll always returns an unsigned mask => it was a really big mistake because then libcec issued a blocking read while there was nothing to read for real) and also notifications for some events were missing but as these events were useless I dropped them...
Have fun
I have also updated libcec because physical addr was not properly retrieved... I will publish it tomorrow

**Comment by steven1758** [comment]
@wolfgar  Oh ,It is great, just have a quickly test. which is very well. We can use the shutdown and reboot now. 

But the HDMI-CEC still can not get work with our SUMSUNG TV,which is ok with your older XBMC 
https://github.com/wolfgar/xbmc/commits/imx-wip
Do you have tried the latest version's CEC,is it ok with your TV ?

I am testing with your latest libcec , xbmc and this  patch in kernel
https://github.com/xbmc-imx6/libcec
https://github.com/xbmc-imx6/xbmc

Thanks again for your effort.  :  )

**Comment by wolfgar** [comment]
Hi,
Yes it works fine faced to my panasonic TV : The TV is powered up by the device then the TV remote can be used to navigate the GUI and when I turn off TV, my device is also turned off...
I will send to you a private mail with an utility to perform additional tests...

**Comment by wolfgar** [comment]
OK, so now it works totally with  (for 3.0.35) :
- The [CEC driver](https://github.com/wolfgar/utilite/blob/8de44c2f1d770e306f7b22636e9c0ad6937d86d4/drivers/mxc/hdmi-cec/mxc_hdmi-cec.c)
- This patch : https://github.com/wolfgar/utilite/commit/5403341d8e35384a4efb4c5a6a00d023c6b668b6

or for kernel 3.10
- https://github.com/wolfgar/linux-linaro-stable-mx6/commit/74fc2e85c080b0ddc2a4b2565eda97c55300303d and https://github.com/wolfgar/linux-linaro-stable-mx6/commit/76796e32b20dd8f34aadad8fd91672017d143812
